version: '3'
services:
  backend:
    build: Backend-rest-api-master
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - uploads:/uploads
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "calendar"
      POSTGRES_USER: "user123"
      POSTGRES_PASSWORD: "password123"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  client:
    build: Frontend-react-master
    stdin_open: true
    tty: true
    ports:
      - "80:3000"
volumes:
  uploads:
  database-data: